### ISSUE TITLE
PIL 11 support

### ISSUE THREAD

**Issue by Mister-42** [Wayrion/Damascus-Cogs#12]
Need to restrict `welcome` to pillow 10 for the moment. 11 is incompatible. Will check later.

**Comment by Wayrion** [comment]
I've pinned the version to 10.4.0. Thank you for reporting this bug :D

**Comment by Mister-42** [comment]
You're fast!
Too fast, as it turns out my report was premature. I apparently had some leftover and incorrect pycache from a recent migration. It works just fine on pillow 11, too.

Sorry about that

**Comment by Wayrion** [comment]
That's fine haha, Pillow is always the problem child anyway. I'll revert the change. Vielen Dank!
